### ISSUE TITLE
Create Sequelize Models

### ISSUE THREAD

**Issue by Meschreiber** [TinaHeiligers/Tulsis#1]
https://learn.fullstackacademy.com/workshop/54b3de126adfdb0b0027d52f/content/54b7e7e33330710b0045bcad/text

Create Product, User, (Shopping Cart) Order, and Review models.

**Comment by TinaHeiligers** [comment]
basic CRUD routes for: Users, Products, Reviews, Order

**Comment by Meschreiber** [comment]
We ended up creating (or updating) the following models: User, Product, Order, OrderItem, Review
